# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11fdb184efcccbd50d0696da477e74ba6e232eac5eacb5e87f052952a8e8dd851d89f61cd56cacc2218568a1782d7ac7053ed69a64591127a845e052556aac1d

test:
  secret_key_base: 307175d24f3532fa7e9f52097c8d6261136b95b3c0010d54b0e176aec61b57acc8d4d75c9c227a764549f213ec6bed04b7361c9c7ea016be8231abc63808077b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
